### PR TITLE
Create calender.cp

### PR DESCRIPTION
**Pull request by jagmr**

### CODE REVIEW

**Comment by yogeshwari-harode** [comment]
Thanks for your contribution.

**Comment by jagmr** [comment]
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>
#define min(a,b) ((a)<(b)?(a):(b))

int main()
{

    int n;
    scanf("%d", &n);
    // Complete the code to print the pattern.
      int k=2*n-1;
        //for row
      for(int row=0;row<k;row++)
        {
            //for col
         for(int col=0;col<k;col++)
         {
          int m=min(row,col)  ;
          m=min(m,k-row-1);
          m=min(m,k-col-1);
         printf("%d ",n-m);
         }
         printf("\n");
        }
    return 0;
}

**Comment by yogeshwari-harode** [comment]
Thank you ☺

**Comment by jagmr** [comment]
#include<iostream>
using namespace std;
int main()
{
for(int i=0;i<=5;i++)
{int k=1;
for(int j=0;j<=10;j++){ // statement of inside loop
if(j>=i&&j<=10-i&&k){
cout<<"*";
k=0;}
else{
cout<<" ";
k=1;}
}
// statement of outer loop
cout<<endl;
}
return 0;
}

**Pull request merged**
