### PR TITLE
Graph

### PR DESCRIPTION
**Pull request by komalmahto**
Breadth First Search Using STL Queue.cpp
Depth First Search Using Recursion.cpp
Depth First Search Using STL Stack.cpp
Krushals Min Cost Spanning Tree.cpp
Prim Min Spanning Tree.cpp

### CODE REVIEW

**Comment by yogeshwari-harode** [comment]
please send any other program or project which you have because this program is not execute successfully..............please send again a pull request with your best program or project

**Comment by komalmahto** [comment]
I have added the correct files again. Please check it.

**Comment by yogeshwari-harode** [comment]
Thanks for your contribution.

**Comment by komalmahto** [comment]
@yogeshwari-harode  Please label my repository as hacktoberfest-accepted.

**Comment by komalmahto** [comment]
@yogeshwari-harode Please label my repository as hacktoberfest-accepted.

**Pull request merged**
